import { test, expect } from '@playwright/test'

for (const theme of ['dark', 'light']) test(`${theme}：沿用归档插件控件，启用状态保持绿色`, async ({ page }) => {
  await page.goto(`/?teams&settings&visual&theme=${theme}`)
  const search = page.locator('.aag-search:visible')
  const select = page.locator('.aag-select-trigger').first()
  await expect(search).toHaveCSS('height', '32px')
  await expect(select).toHaveCSS('height', '32px')
  await expect(search).toHaveCSS('background-color', await select.evaluate(el => getComputedStyle(el).backgroundColor))
  await expect(search).toHaveCSS('border-width', '1px')
  await select.click()
  await expect(page.getByRole('menuitem').first()).toBeVisible()
  await page.keyboard.press('Escape')
  await search.focus()
  await expect(search).toHaveCSS('outline-style', 'none')
  await page.screenshot({ path: `test-results/archive-controls-${theme}.png` })
  await page.getByRole('tab', { name: '专家团', exact: true }).click()
  const teamCard = page.getByTestId('team-card').first()
  await expect(page.getByRole('button', { name: '新建专家团', exact: true })).toBeVisible()
  const firstSwitch = teamCard.getByRole('switch')
  await firstSwitch.click()
  await expect(firstSwitch).toHaveAttribute('aria-checked', 'false')
  await page.screenshot({ path: `test-results/archive-teams-${theme}.png` })
})
