import { test, expect } from '@playwright/test'

for (const theme of ['dark', 'light']) test(`${theme}：沿用归档插件控件，启用状态保持绿色`, async ({ page }) => {
  await page.goto(`/?teams&settings&visual&theme=${theme}`)
  const search = page.locator('.aag-search')
  const select = page.locator('.aag-select-trigger').first()
  await expect(search).toHaveCSS('height', '32px')
  await expect(select).toHaveCSS('height', '32px')
  await expect(search).toHaveCSS('background-color', await select.evaluate(el => getComputedStyle(el).backgroundColor))
  await expect(search).toHaveCSS('border-width', '1px')
  await expect(page.getByRole('button', { name: '新建专家', exact: true })).toHaveCSS('border-radius', '8px')
  await expect(page.locator('.aag-switch-input:checked + .aag-switch-track').first()).toHaveCSS('background-color', 'rgb(37, 207, 105)')
  await select.click()
  await expect(page.locator('.aag-select-menu')).toHaveCSS('border-radius', '10px')
  await expect(page.getByRole('option').first()).toHaveCSS('min-height', '32px')
  await page.keyboard.press('Escape')
  await search.focus()
  await expect(search).toHaveCSS('outline-style', 'none')
  await page.screenshot({ path: `test-results/archive-controls-${theme}.png` })
  await page.getByRole('tab', { name: '专家团', exact: true }).click()
  const teamCard = page.getByTestId('team-card').first()
  await expect(teamCard.locator('.aag-switch-track')).toHaveCSS('background-color', 'rgb(37, 207, 105)')
  await expect(page.getByRole('button', { name: '新建专家团', exact: true })).toHaveCSS('border-radius', '8px')
  const firstSwitch = teamCard.locator('.aag-switch-input')
  await teamCard.locator('.aag-switch-track').click()
  await expect(firstSwitch).not.toBeChecked()
  await expect(teamCard.locator('.aag-switch-track')).not.toHaveCSS('background-color', 'rgb(37, 207, 105)')
  await page.screenshot({ path: `test-results/archive-teams-${theme}.png` })
})
